name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u Teshager21 --password-stdin


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/teshager21/credit-risk-model-altdata:latest

      # OPTIONAL — Deploy to remote server over SSH
      # Uncomment if you want automatic deploys

      # - name: Deploy to remote server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull ghcr.io/teshager21/credit-risk-model-altdata:latest
      #       docker stop credit-risk-api || true
      #       docker rm credit-risk-api || true
      #       docker run -d --name credit-risk-api -p 8000:8000 ghcr.io/teshager21/credit-risk-model-altdata:latest
